// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: roster.proto

package service

import (
	proto "github.com/golang/protobuf/proto"
	model "github.com/ronaksoft/dclock/model"
	_ "github.com/ronaksoft/rony"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PageSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page       uint32 `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	ReplicaSet uint64 `protobuf:"varint,2,opt,name=ReplicaSet,proto3" json:"ReplicaSet,omitempty"`
	Replace    bool   `protobuf:"varint,3,opt,name=Replace,proto3" json:"Replace,omitempty"`
}

func (x *PageSetRequest) Reset() {
	*x = PageSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roster_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageSetRequest) ProtoMessage() {}

func (x *PageSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_roster_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageSetRequest.ProtoReflect.Descriptor instead.
func (*PageSetRequest) Descriptor() ([]byte, []int) {
	return file_roster_proto_rawDescGZIP(), []int{0}
}

func (x *PageSetRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageSetRequest) GetReplicaSet() uint64 {
	if x != nil {
		return x.ReplicaSet
	}
	return 0
}

func (x *PageSetRequest) GetReplace() bool {
	if x != nil {
		return x.Replace
	}
	return false
}

type PageGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page       uint32 `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	ReplicaSet uint64 `protobuf:"varint,2,opt,name=ReplicaSet,proto3" json:"ReplicaSet,omitempty"`
	CreateNew  bool   `protobuf:"varint,3,opt,name=CreateNew,proto3" json:"CreateNew,omitempty"`
}

func (x *PageGetRequest) Reset() {
	*x = PageGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roster_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageGetRequest) ProtoMessage() {}

func (x *PageGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_roster_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageGetRequest.ProtoReflect.Descriptor instead.
func (*PageGetRequest) Descriptor() ([]byte, []int) {
	return file_roster_proto_rawDescGZIP(), []int{1}
}

func (x *PageGetRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageGetRequest) GetReplicaSet() uint64 {
	if x != nil {
		return x.ReplicaSet
	}
	return 0
}

func (x *PageGetRequest) GetCreateNew() bool {
	if x != nil {
		return x.CreateNew
	}
	return false
}

type PageListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReplicaSet uint64 `protobuf:"varint,1,opt,name=ReplicaSet,proto3" json:"ReplicaSet,omitempty"`
}

func (x *PageListRequest) Reset() {
	*x = PageListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roster_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageListRequest) ProtoMessage() {}

func (x *PageListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_roster_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageListRequest.ProtoReflect.Descriptor instead.
func (*PageListRequest) Descriptor() ([]byte, []int) {
	return file_roster_proto_rawDescGZIP(), []int{2}
}

func (x *PageListRequest) GetReplicaSet() uint64 {
	if x != nil {
		return x.ReplicaSet
	}
	return 0
}

type PagesMany struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pages []*model.Page `protobuf:"bytes,1,rep,name=Pages,proto3" json:"Pages,omitempty"`
}

func (x *PagesMany) Reset() {
	*x = PagesMany{}
	if protoimpl.UnsafeEnabled {
		mi := &file_roster_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PagesMany) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesMany) ProtoMessage() {}

func (x *PagesMany) ProtoReflect() protoreflect.Message {
	mi := &file_roster_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesMany.ProtoReflect.Descriptor instead.
func (*PagesMany) Descriptor() ([]byte, []int) {
	return file_roster_proto_rawDescGZIP(), []int{3}
}

func (x *PagesMany) GetPages() []*model.Page {
	if x != nil {
		return x.Pages
	}
	return nil
}

var File_roster_proto protoreflect.FileDescriptor

var file_roster_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x72, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x6f, 0x6e, 0x61, 0x6b, 0x73, 0x6f, 0x66, 0x74, 0x2f, 0x72, 0x6f,
	0x6e, 0x79, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x10, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x70, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x5e, 0x0a, 0x0e, 0x50, 0x61, 0x67, 0x65, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x53, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x52, 0x65,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x53, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x52, 0x65, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x52, 0x65, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x22, 0x62, 0x0a, 0x0e, 0x50, 0x61, 0x67, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x53, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x52, 0x65,
	0x70, 0x6c, 0x69, 0x63, 0x61, 0x53, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4e, 0x65, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4e, 0x65, 0x77, 0x22, 0x31, 0x0a, 0x0f, 0x50, 0x61, 0x67, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x53, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x52,
	0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x53, 0x65, 0x74, 0x22, 0x2e, 0x0a, 0x09, 0x50, 0x61, 0x67,
	0x65, 0x73, 0x4d, 0x61, 0x6e, 0x79, 0x12, 0x21, 0x0a, 0x05, 0x50, 0x61, 0x67, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x61,
	0x67, 0x65, 0x52, 0x05, 0x50, 0x61, 0x67, 0x65, 0x73, 0x32, 0xb6, 0x01, 0x0a, 0x06, 0x52, 0x6f,
	0x73, 0x74, 0x65, 0x72, 0x12, 0x35, 0x0a, 0x07, 0x50, 0x61, 0x67, 0x65, 0x47, 0x65, 0x74, 0x12,
	0x17, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x50, 0x61, 0x67, 0x65, 0x22, 0x04, 0x90, 0xb5, 0x18, 0x01, 0x12, 0x35, 0x0a, 0x07, 0x50,
	0x61, 0x67, 0x65, 0x53, 0x65, 0x74, 0x12, 0x17, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x50, 0x61, 0x67, 0x65, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x22, 0x04, 0x90, 0xb5,
	0x18, 0x01, 0x12, 0x38, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x73, 0x4d, 0x61, 0x6e, 0x79, 0x1a, 0x04, 0x88, 0xb5,
	0x18, 0x01, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x72, 0x6f, 0x6e, 0x61, 0x6b, 0x73, 0x6f, 0x66, 0x74, 0x2f, 0x64, 0x63, 0x6c, 0x6f, 0x63,
	0x6b, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_roster_proto_rawDescOnce sync.Once
	file_roster_proto_rawDescData = file_roster_proto_rawDesc
)

func file_roster_proto_rawDescGZIP() []byte {
	file_roster_proto_rawDescOnce.Do(func() {
		file_roster_proto_rawDescData = protoimpl.X.CompressGZIP(file_roster_proto_rawDescData)
	})
	return file_roster_proto_rawDescData
}

var file_roster_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_roster_proto_goTypes = []interface{}{
	(*PageSetRequest)(nil),  // 0: service.PageSetRequest
	(*PageGetRequest)(nil),  // 1: service.PageGetRequest
	(*PageListRequest)(nil), // 2: service.PageListRequest
	(*PagesMany)(nil),       // 3: service.PagesMany
	(*model.Page)(nil),      // 4: model.Page
}
var file_roster_proto_depIdxs = []int32{
	4, // 0: service.PagesMany.Pages:type_name -> model.Page
	1, // 1: service.Roster.PageGet:input_type -> service.PageGetRequest
	0, // 2: service.Roster.PageSet:input_type -> service.PageSetRequest
	2, // 3: service.Roster.PageList:input_type -> service.PageListRequest
	4, // 4: service.Roster.PageGet:output_type -> model.Page
	4, // 5: service.Roster.PageSet:output_type -> model.Page
	3, // 6: service.Roster.PageList:output_type -> service.PagesMany
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_roster_proto_init() }
func file_roster_proto_init() {
	if File_roster_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_roster_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roster_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roster_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_roster_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PagesMany); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_roster_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_roster_proto_goTypes,
		DependencyIndexes: file_roster_proto_depIdxs,
		MessageInfos:      file_roster_proto_msgTypes,
	}.Build()
	File_roster_proto = out.File
	file_roster_proto_rawDesc = nil
	file_roster_proto_goTypes = nil
	file_roster_proto_depIdxs = nil
}
